// AUTO-GENERATED from db/schema.sql — kolon adları SQL enjeksiyonuna karşı beyaz liste olarak kullanılır.
// Veritabanı şeması değişirse: npm run db:columns

export interface ColumnDef { name: string; type: string; }

export interface ResourceDef {
  table: string;
  primaryKey: string;
  columns: ColumnDef[];
  jsonColumns: string[];
  timestamps: ("createdAt" | "updatedAt")[];
}

export const RESOURCES: Record<string, ResourceDef> = {
  contacts: {
    table: "contacts",
    primaryKey: "id",
    columns: [
      { name: "id", type: "bigint" },
      { name: "code", type: "varchar" },
      { name: "name", type: "varchar" },
      { name: "companyTitle", type: "varchar" },
      { name: "contactPerson", type: "varchar" },
      { name: "type", type: "enum" },
      { name: "category", type: "varchar" },
      { name: "email", type: "varchar" },
      { name: "phone", type: "varchar" },
      { name: "mobile", type: "varchar" },
      { name: "website", type: "varchar" },
      { name: "address", type: "text" },
      { name: "shippingAddress", type: "text" },
      { name: "city", type: "varchar" },
      { name: "district", type: "varchar" },
      { name: "country", type: "varchar" },
      { name: "taxOffice", type: "varchar" },
      { name: "taxNumber", type: "varchar" },
      { name: "tcKimlik", type: "varchar" },
      { name: "paymentTermDays", type: "int" },
      { name: "creditLimit", type: "decimal" },
      { name: "discountRate", type: "decimal" },
      { name: "bankName", type: "varchar" },
      { name: "iban", type: "varchar" },
      { name: "bankAccountName", type: "varchar" },
      { name: "balance", type: "decimal" },
      { name: "currency", type: "varchar" },
      { name: "accountCode", type: "varchar" },
      { name: "notes", type: "text" },
      { name: "createdAt", type: "datetime" },
      { name: "updatedAt", type: "datetime" },
      { name: "version", type: "int" },
    ],
    jsonColumns: [],
    timestamps: ["createdAt","updatedAt"],
  },
  assortmentTemplates: {
    table: "assortmentTemplates",
    primaryKey: "id",
    columns: [
      { name: "id", type: "bigint" },
      { name: "name", type: "varchar" },
      { name: "items", type: "json" },
      { name: "version", type: "int" },
    ],
    jsonColumns: ["items"],
    timestamps: [],
  },
  barcodeTemplates: {
    table: "barcodeTemplates",
    primaryKey: "id",
    columns: [
      { name: "id", type: "bigint" },
      { name: "name", type: "varchar" },
      { name: "description", type: "text" },
      { name: "type", type: "varchar" },
      { name: "presetSize", type: "varchar" },
      { name: "widthMm", type: "decimal" },
      { name: "heightMm", type: "decimal" },
      { name: "orientation", type: "varchar" },
      { name: "isDefault", type: "tinyint" },
      { name: "config", type: "json" },
      { name: "createdAt", type: "datetime" },
      { name: "updatedAt", type: "datetime" },
      { name: "version", type: "int" },
    ],
    jsonColumns: ["config"],
    timestamps: ["createdAt","updatedAt"],
  },
  products: {
    table: "products",
    primaryKey: "id",
    columns: [
      { name: "id", type: "bigint" },
      { name: "code", type: "varchar" },
      { name: "name", type: "varchar" },
      { name: "categoryType", type: "varchar" },
      { name: "hasSizeVariants", type: "tinyint" },
      { name: "subType", type: "varchar" },
      { name: "moldCode", type: "varchar" },
      { name: "moldGroup", type: "varchar" },
      { name: "documentNo", type: "varchar" },
      { name: "unit", type: "varchar" },
      { name: "secondaryUnit", type: "varchar" },
      { name: "multiplier", type: "decimal" },
      { name: "stock", type: "decimal" },
      { name: "minStock", type: "decimal" },
      { name: "buyingPrice", type: "decimal" },
      { name: "sellingPrice", type: "decimal" },
      { name: "isRawMaterial", type: "tinyint" },
      { name: "barcode", type: "varchar" },
      { name: "colorBoxBarcodes", type: "json" },
      { name: "variantBarcodes", type: "json" },
      { name: "isFootwear", type: "tinyint" },
      { name: "colors", type: "json" },
      { name: "assortmentTemplateId", type: "bigint" },
      { name: "assortment", type: "json" },
      { name: "category", type: "varchar" },
      { name: "brand", type: "varchar" },
      { name: "image", type: "longtext" },
      { name: "colorImages", type: "json" },
      { name: "shelf", type: "varchar" },
      { name: "location", type: "varchar" },
      { name: "accountingCode", type: "varchar" },
      { name: "salesAccountCode", type: "varchar" },
      { name: "purchaseAccountCode", type: "varchar" },
      { name: "vatRate", type: "decimal" },
      { name: "preferredSupplierId", type: "bigint" },
      { name: "preferredSupplierName", type: "varchar" },
      { name: "notes", type: "text" },
      { name: "createdAt", type: "datetime" },
      { name: "updatedAt", type: "datetime" },
      { name: "version", type: "int" },
    ],
    jsonColumns: ["colorBoxBarcodes","variantBarcodes","colors","assortment","colorImages"],
    timestamps: ["createdAt","updatedAt"],
  },
  recipes: {
    table: "recipes",
    primaryKey: "id",
    columns: [
      { name: "id", type: "bigint" },
      { name: "productId", type: "bigint" },
      { name: "targetColor", type: "varchar" },
      { name: "name", type: "varchar" },
      { name: "ingredients", type: "json" },
      { name: "notes", type: "text" },
      { name: "laborCost", type: "decimal" },
      { name: "estimatedTimeMinutes", type: "int" },
      { name: "createdAt", type: "datetime" },
      { name: "updatedAt", type: "datetime" },
      { name: "version", type: "int" },
    ],
    jsonColumns: ["ingredients"],
    timestamps: ["createdAt","updatedAt"],
  },
  workOrders: {
    table: "workOrders",
    primaryKey: "id",
    columns: [
      { name: "id", type: "bigint" },
      { name: "productId", type: "bigint" },
      { name: "quantity", type: "decimal" },
      { name: "status", type: "enum" },
      { name: "createdAt", type: "datetime" },
      { name: "completedAt", type: "datetime" },
      { name: "targetDate", type: "datetime" },
      { name: "orderId", type: "bigint" },
      { name: "orderItemId", type: "bigint" },
      { name: "orderNumber", type: "varchar" },
      { name: "customerName", type: "varchar" },
      { name: "customerCode", type: "varchar" },
      { name: "orderDate", type: "datetime" },
      { name: "documentNo", type: "varchar" },
      { name: "moldCode", type: "varchar" },
      { name: "moldGroup", type: "varchar" },
      { name: "color", type: "varchar" },
      { name: "size", type: "varchar" },
      { name: "assortmentBreakdown", type: "json" },
      { name: "currentStage", type: "varchar" },
      { name: "stages", type: "json" },
      { name: "materialStatus", type: "varchar" },
      { name: "recipeId", type: "bigint" },
      { name: "barcode", type: "varchar" },
      { name: "notes", type: "text" },
      { name: "operator", type: "varchar" },
      { name: "version", type: "int" },
    ],
    jsonColumns: ["assortmentBreakdown","stages"],
    timestamps: ["createdAt"],
  },
  inventoryLogs: {
    table: "inventoryLogs",
    primaryKey: "id",
    columns: [
      { name: "id", type: "bigint" },
      { name: "productId", type: "bigint" },
      { name: "type", type: "enum" },
      { name: "quantity", type: "decimal" },
      { name: "date", type: "datetime" },
      { name: "description", type: "text" },
      { name: "color", type: "varchar" },
      { name: "size", type: "varchar" },
      { name: "version", type: "int" },
    ],
    jsonColumns: [],
    timestamps: [],
  },
  transactions: {
    table: "transactions",
    primaryKey: "id",
    columns: [
      { name: "id", type: "bigint" },
      { name: "contactId", type: "bigint" },
      { name: "type", type: "enum" },
      { name: "amount", type: "decimal" },
      { name: "description", type: "text" },
      { name: "date", type: "datetime" },
      { name: "category", type: "varchar" },
      { name: "paymentMethod", type: "varchar" },
      { name: "documentNo", type: "varchar" },
      { name: "orderId", type: "bigint" },
      { name: "version", type: "int" },
    ],
    jsonColumns: [],
    timestamps: [],
  },
  settings: {
    table: "settings",
    primaryKey: "id",
    columns: [
      { name: "id", type: "varchar" },
      { name: "barcodeType", type: "varchar" },
      { name: "barcodePrefix", type: "varchar" },
      { name: "nextBarcodeSequence", type: "bigint" },
      { name: "movementsReset", type: "tinyint" },
      { name: "productionReset", type: "tinyint" },
      { name: "company", type: "json" },
      { name: "stock", type: "json" },
      { name: "order", type: "json" },
      { name: "production", type: "json" },
      { name: "finance", type: "json" },
      { name: "hr", type: "json" },
      { name: "version", type: "int" },
    ],
    jsonColumns: ["company","stock","order","production","finance","hr"],
    timestamps: [],
  },
  orders: {
    table: "orders",
    primaryKey: "id",
    columns: [
      { name: "id", type: "bigint" },
      { name: "type", type: "enum" },
      { name: "orderNumber", type: "varchar" },
      { name: "contactId", type: "bigint" },
      { name: "date", type: "datetime" },
      { name: "deliveryDate", type: "datetime" },
      { name: "status", type: "enum" },
      { name: "invoicingStatus", type: "enum" },
      { name: "invoicedTotal", type: "decimal" },
      { name: "totalAmount", type: "decimal" },
      { name: "taxAmount", type: "decimal" },
      { name: "discountAmount", type: "decimal" },
      { name: "grandTotal", type: "decimal" },
      { name: "notes", type: "text" },
      { name: "currency", type: "varchar" },
      { name: "createdAt", type: "datetime" },
      { name: "updatedAt", type: "datetime" },
      { name: "version", type: "int" },
    ],
    jsonColumns: [],
    timestamps: ["createdAt","updatedAt"],
  },
  orderItems: {
    table: "orderItems",
    primaryKey: "id",
    columns: [
      { name: "id", type: "bigint" },
      { name: "orderId", type: "bigint" },
      { name: "productId", type: "bigint" },
      { name: "color", type: "varchar" },
      { name: "size", type: "varchar" },
      { name: "quantity", type: "decimal" },
      { name: "shippedQuantity", type: "decimal" },
      { name: "invoicedQuantity", type: "decimal" },
      { name: "unitPrice", type: "decimal" },
      { name: "taxRate", type: "decimal" },
      { name: "discountRate", type: "decimal" },
      { name: "total", type: "decimal" },
      { name: "version", type: "int" },
    ],
    jsonColumns: [],
    timestamps: [],
  },
  invoices: {
    table: "invoices",
    primaryKey: "id",
    columns: [
      { name: "id", type: "bigint" },
      { name: "invoiceNumber", type: "varchar" },
      { name: "type", type: "enum" },
      { name: "scenario", type: "enum" },
      { name: "contactId", type: "bigint" },
      { name: "orderId", type: "bigint" },
      { name: "orderNumber", type: "varchar" },
      { name: "waybillId", type: "bigint" },
      { name: "waybillNumber", type: "varchar" },
      { name: "date", type: "datetime" },
      { name: "dueDate", type: "datetime" },
      { name: "ettn", type: "varchar" },
      { name: "subtotal", type: "decimal" },
      { name: "discountTotal", type: "decimal" },
      { name: "taxTotal", type: "decimal" },
      { name: "withholdingRate", type: "decimal" },
      { name: "withholdingAmount", type: "decimal" },
      { name: "grandTotal", type: "decimal" },
      { name: "currency", type: "varchar" },
      { name: "exchangeRate", type: "decimal" },
      { name: "paymentStatus", type: "enum" },
      { name: "paidAmount", type: "decimal" },
      { name: "status", type: "enum" },
      { name: "notes", type: "text" },
      { name: "isStockDeducted", type: "tinyint" },
      { name: "createdAt", type: "datetime" },
      { name: "updatedAt", type: "datetime" },
      { name: "version", type: "int" },
    ],
    jsonColumns: [],
    timestamps: ["createdAt","updatedAt"],
  },
  invoiceItems: {
    table: "invoiceItems",
    primaryKey: "id",
    columns: [
      { name: "id", type: "bigint" },
      { name: "invoiceId", type: "bigint" },
      { name: "productId", type: "bigint" },
      { name: "orderItemId", type: "bigint" },
      { name: "productCode", type: "varchar" },
      { name: "productName", type: "varchar" },
      { name: "color", type: "varchar" },
      { name: "size", type: "varchar" },
      { name: "quantity", type: "decimal" },
      { name: "unit", type: "varchar" },
      { name: "unitPrice", type: "decimal" },
      { name: "discountRate", type: "decimal" },
      { name: "discountAmount", type: "decimal" },
      { name: "taxRate", type: "decimal" },
      { name: "taxAmount", type: "decimal" },
      { name: "total", type: "decimal" },
      { name: "version", type: "int" },
    ],
    jsonColumns: [],
    timestamps: [],
  },
  waybills: {
    table: "waybills",
    primaryKey: "id",
    columns: [
      { name: "id", type: "bigint" },
      { name: "waybillNumber", type: "varchar" },
      { name: "type", type: "enum" },
      { name: "scenario", type: "enum" },
      { name: "contactId", type: "bigint" },
      { name: "contactName", type: "varchar" },
      { name: "orderId", type: "bigint" },
      { name: "orderNumber", type: "varchar" },
      { name: "date", type: "datetime" },
      { name: "shippingDate", type: "datetime" },
      { name: "dispatchDate", type: "datetime" },
      { name: "dispatchTime", type: "varchar" },
      { name: "carrierTitle", type: "varchar" },
      { name: "carrierTaxNo", type: "varchar" },
      { name: "driverName", type: "varchar" },
      { name: "driverTc", type: "varchar" },
      { name: "vehiclePlate", type: "varchar" },
      { name: "trailerPlate", type: "varchar" },
      { name: "deliveryAddress", type: "text" },
      { name: "ettn", type: "varchar" },
      { name: "subtotal", type: "decimal" },
      { name: "discountTotal", type: "decimal" },
      { name: "taxTotal", type: "decimal" },
      { name: "grandTotal", type: "decimal" },
      { name: "totalQuantity", type: "decimal" },
      { name: "currency", type: "varchar" },
      { name: "status", type: "enum" },
      { name: "isStockDeducted", type: "tinyint" },
      { name: "invoicedStatus", type: "enum" },
      { name: "invoiceId", type: "bigint" },
      { name: "invoiceNumber", type: "varchar" },
      { name: "notes", type: "text" },
      { name: "createdAt", type: "datetime" },
      { name: "updatedAt", type: "datetime" },
      { name: "version", type: "int" },
    ],
    jsonColumns: [],
    timestamps: ["createdAt","updatedAt"],
  },
  waybillItems: {
    table: "waybillItems",
    primaryKey: "id",
    columns: [
      { name: "id", type: "bigint" },
      { name: "waybillId", type: "bigint" },
      { name: "productId", type: "bigint" },
      { name: "orderItemId", type: "bigint" },
      { name: "productCode", type: "varchar" },
      { name: "productName", type: "varchar" },
      { name: "color", type: "varchar" },
      { name: "size", type: "varchar" },
      { name: "quantity", type: "decimal" },
      { name: "unit", type: "varchar" },
      { name: "unitPrice", type: "decimal" },
      { name: "discountRate", type: "decimal" },
      { name: "discountAmount", type: "decimal" },
      { name: "taxRate", type: "decimal" },
      { name: "taxAmount", type: "decimal" },
      { name: "total", type: "decimal" },
      { name: "version", type: "int" },
    ],
    jsonColumns: [],
    timestamps: [],
  },
  accounts: {
    table: "accounts",
    primaryKey: "id",
    columns: [
      { name: "id", type: "bigint" },
      { name: "code", type: "varchar" },
      { name: "name", type: "varchar" },
      { name: "type", type: "enum" },
      { name: "level", type: "int" },
      { name: "parentCode", type: "varchar" },
      { name: "currency", type: "varchar" },
      { name: "description", type: "text" },
      { name: "isSystem", type: "tinyint" },
      { name: "isActive", type: "tinyint" },
      { name: "version", type: "int" },
    ],
    jsonColumns: [],
    timestamps: [],
  },
  journalEntries: {
    table: "journalEntries",
    primaryKey: "id",
    columns: [
      { name: "id", type: "bigint" },
      { name: "entryNumber", type: "varchar" },
      { name: "entryType", type: "enum" },
      { name: "date", type: "datetime" },
      { name: "description", type: "text" },
      { name: "documentType", type: "varchar" },
      { name: "documentId", type: "bigint" },
      { name: "documentNumber", type: "varchar" },
      { name: "lines", type: "json" },
      { name: "totalDebit", type: "decimal" },
      { name: "totalCredit", type: "decimal" },
      { name: "isBalanced", type: "tinyint" },
      { name: "status", type: "enum" },
      { name: "createdAt", type: "datetime" },
      { name: "updatedAt", type: "datetime" },
      { name: "version", type: "int" },
    ],
    jsonColumns: ["lines"],
    timestamps: ["createdAt","updatedAt"],
  },
  cashBoxes: {
    table: "cashBoxes",
    primaryKey: "id",
    columns: [
      { name: "id", type: "bigint" },
      { name: "code", type: "varchar" },
      { name: "name", type: "varchar" },
      { name: "accountCode", type: "varchar" },
      { name: "currency", type: "varchar" },
      { name: "balance", type: "decimal" },
      { name: "responsiblePerson", type: "varchar" },
      { name: "notes", type: "text" },
      { name: "createdAt", type: "datetime" },
      { name: "version", type: "int" },
    ],
    jsonColumns: [],
    timestamps: ["createdAt"],
  },
  bankAccounts: {
    table: "bankAccounts",
    primaryKey: "id",
    columns: [
      { name: "id", type: "bigint" },
      { name: "bankName", type: "varchar" },
      { name: "branchName", type: "varchar" },
      { name: "accountNumber", type: "varchar" },
      { name: "iban", type: "varchar" },
      { name: "accountCode", type: "varchar" },
      { name: "currency", type: "varchar" },
      { name: "balance", type: "decimal" },
      { name: "notes", type: "text" },
      { name: "createdAt", type: "datetime" },
      { name: "version", type: "int" },
    ],
    jsonColumns: [],
    timestamps: ["createdAt"],
  },
  checks: {
    table: "checks",
    primaryKey: "id",
    columns: [
      { name: "id", type: "bigint" },
      { name: "type", type: "enum" },
      { name: "portfolioNumber", type: "varchar" },
      { name: "serialNumber", type: "varchar" },
      { name: "bankName", type: "varchar" },
      { name: "branchName", type: "varchar" },
      { name: "accountNumber", type: "varchar" },
      { name: "drawer", type: "varchar" },
      { name: "drawerTaxNumber", type: "varchar" },
      { name: "contactId", type: "bigint" },
      { name: "contactName", type: "varchar" },
      { name: "endorsedToContactId", type: "bigint" },
      { name: "endorsedToContactName", type: "varchar" },
      { name: "issueDate", type: "datetime" },
      { name: "dueDate", type: "datetime" },
      { name: "amount", type: "decimal" },
      { name: "currency", type: "varchar" },
      { name: "status", type: "enum" },
      { name: "statusChangeDate", type: "datetime" },
      { name: "statusNotes", type: "text" },
      { name: "accountCode", type: "varchar" },
      { name: "journalEntryId", type: "bigint" },
      { name: "targetBankAccountId", type: "bigint" },
      { name: "targetCashBoxId", type: "bigint" },
      { name: "notes", type: "text" },
      { name: "createdAt", type: "datetime" },
      { name: "version", type: "int" },
    ],
    jsonColumns: [],
    timestamps: ["createdAt"],
  },
  collectionReceipts: {
    table: "collectionReceipts",
    primaryKey: "id",
    columns: [
      { name: "id", type: "bigint" },
      { name: "receiptNumber", type: "varchar" },
      { name: "type", type: "enum" },
      { name: "date", type: "datetime" },
      { name: "contactId", type: "bigint" },
      { name: "contactName", type: "varchar" },
      { name: "instrument", type: "enum" },
      { name: "cashBoxId", type: "bigint" },
      { name: "bankAccountId", type: "bigint" },
      { name: "checkId", type: "bigint" },
      { name: "amount", type: "decimal" },
      { name: "currency", type: "varchar" },
      { name: "description", type: "text" },
      { name: "invoiceId", type: "bigint" },
      { name: "invoiceNumber", type: "varchar" },
      { name: "journalEntryId", type: "bigint" },
      { name: "isAccounted", type: "tinyint" },
      { name: "createdAt", type: "datetime" },
      { name: "version", type: "int" },
    ],
    jsonColumns: [],
    timestamps: ["createdAt"],
  },
  employees: {
    table: "employees",
    primaryKey: "id",
    columns: [
      { name: "id", type: "bigint" },
      { name: "employeeCode", type: "varchar" },
      { name: "name", type: "varchar" },
      { name: "tcNo", type: "varchar" },
      { name: "phone", type: "varchar" },
      { name: "email", type: "varchar" },
      { name: "department", type: "varchar" },
      { name: "position", type: "varchar" },
      { name: "hireDate", type: "datetime" },
      { name: "terminationDate", type: "datetime" },
      { name: "status", type: "enum" },
      { name: "sgkStatus", type: "enum" },
      { name: "salaryType", type: "enum" },
      { name: "baseSalary", type: "decimal" },
      { name: "agreedNetSalary", type: "decimal" },
      { name: "paymentMethod", type: "enum" },
      { name: "bankName", type: "varchar" },
      { name: "iban", type: "varchar" },
      { name: "entitledAnnualLeave", type: "int" },
      { name: "usedAnnualLeave", type: "int" },
      { name: "bloodGroup", type: "varchar" },
      { name: "emergencyContact", type: "varchar" },
      { name: "address", type: "text" },
      { name: "notes", type: "text" },
      { name: "createdAt", type: "datetime" },
      { name: "version", type: "int" },
    ],
    jsonColumns: [],
    timestamps: ["createdAt"],
  },
  attendanceRecords: {
    table: "attendanceRecords",
    primaryKey: "id",
    columns: [
      { name: "id", type: "bigint" },
      { name: "employeeId", type: "bigint" },
      { name: "date", type: "varchar" },
      { name: "month", type: "int" },
      { name: "year", type: "int" },
      { name: "status", type: "varchar" },
      { name: "checkInTime", type: "varchar" },
      { name: "checkOutTime", type: "varchar" },
      { name: "normalHours", type: "decimal" },
      { name: "overtimeHours", type: "decimal" },
      { name: "notes", type: "text" },
      { name: "version", type: "int" },
    ],
    jsonColumns: [],
    timestamps: [],
  },
  leaveRequests: {
    table: "leaveRequests",
    primaryKey: "id",
    columns: [
      { name: "id", type: "bigint" },
      { name: "employeeId", type: "bigint" },
      { name: "employeeName", type: "varchar" },
      { name: "leaveType", type: "varchar" },
      { name: "startDate", type: "varchar" },
      { name: "endDate", type: "varchar" },
      { name: "days", type: "decimal" },
      { name: "status", type: "enum" },
      { name: "reason", type: "text" },
      { name: "approvedBy", type: "varchar" },
      { name: "createdAt", type: "datetime" },
      { name: "version", type: "int" },
    ],
    jsonColumns: [],
    timestamps: ["createdAt"],
  },
  advanceRequests: {
    table: "advanceRequests",
    primaryKey: "id",
    columns: [
      { name: "id", type: "bigint" },
      { name: "employeeId", type: "bigint" },
      { name: "employeeName", type: "varchar" },
      { name: "date", type: "datetime" },
      { name: "amount", type: "decimal" },
      { name: "description", type: "text" },
      { name: "month", type: "int" },
      { name: "year", type: "int" },
      { name: "status", type: "enum" },
      { name: "isDeducted", type: "tinyint" },
      { name: "createdAt", type: "datetime" },
      { name: "version", type: "int" },
    ],
    jsonColumns: [],
    timestamps: ["createdAt"],
  },
  payrollRecords: {
    table: "payrollRecords",
    primaryKey: "id",
    columns: [
      { name: "id", type: "bigint" },
      { name: "employeeId", type: "bigint" },
      { name: "employeeName", type: "varchar" },
      { name: "employeeCode", type: "varchar" },
      { name: "department", type: "varchar" },
      { name: "month", type: "int" },
      { name: "year", type: "int" },
      { name: "sgkStatus", type: "enum" },
      { name: "salaryType", type: "varchar" },
      { name: "daysWorked", type: "decimal" },
      { name: "weeklyRestDays", type: "decimal" },
      { name: "paidLeaveDays", type: "decimal" },
      { name: "unpaidLeaveDays", type: "decimal" },
      { name: "absentDays", type: "decimal" },
      { name: "totalDays", type: "decimal" },
      { name: "overtimeHours", type: "decimal" },
      { name: "baseSalary", type: "decimal" },
      { name: "basePay", type: "decimal" },
      { name: "overtimePay", type: "decimal" },
      { name: "bonusPay", type: "decimal" },
      { name: "totalGrossPay", type: "decimal" },
      { name: "employeeSgkShare", type: "decimal" },
      { name: "employeeUnemploymentShare", type: "decimal" },
      { name: "incomeTaxBase", type: "decimal" },
      { name: "previousCumulativeTaxBase", type: "decimal" },
      { name: "cumulativeTaxBase", type: "decimal" },
      { name: "appliedTaxRate", type: "decimal" },
      { name: "incomeTax", type: "decimal" },
      { name: "stampTax", type: "decimal" },
      { name: "totalLegalDeductions", type: "decimal" },
      { name: "totalGrossPayKurus", type: "bigint" },
      { name: "employeeSgkShareKurus", type: "bigint" },
      { name: "employeeUnemploymentShareKurus", type: "bigint" },
      { name: "incomeTaxKurus", type: "bigint" },
      { name: "stampTaxKurus", type: "bigint" },
      { name: "netSalaryKurus", type: "bigint" },
      { name: "totalEmployerCostKurus", type: "bigint" },
      { name: "advanceDeduction", type: "decimal" },
      { name: "otherDeductions", type: "decimal" },
      { name: "netSalary", type: "decimal" },
      { name: "employerSgkShare", type: "decimal" },
      { name: "employerUnemploymentShare", type: "decimal" },
      { name: "totalEmployerCost", type: "decimal" },
      { name: "paymentStatus", type: "enum" },
      { name: "paidDate", type: "datetime" },
      { name: "paidFromType", type: "enum" },
      { name: "paidFromId", type: "bigint" },
      { name: "isAccounted", type: "tinyint" },
      { name: "journalEntryId", type: "bigint" },
      { name: "notes", type: "text" },
      { name: "createdAt", type: "datetime" },
      { name: "version", type: "int" },
    ],
    jsonColumns: [],
    timestamps: ["createdAt"],
  },
  periodLocks: {
    table: "periodLocks",
    primaryKey: "id",
    columns: [
      { name: "id", type: "bigint" },
      { name: "month", type: "int" },
      { name: "year", type: "int" },
      { name: "isLocked", type: "tinyint" },
      { name: "lockedAt", type: "datetime" },
      { name: "lockedBy", type: "varchar" },
      { name: "notes", type: "text" },
      { name: "version", type: "int" },
    ],
    jsonColumns: [],
    timestamps: [],
  },
  roles: {
    table: "roles",
    primaryKey: "id",
    columns: [
      { name: "id", type: "bigint" },
      { name: "code", type: "varchar" },
      { name: "name", type: "varchar" },
      { name: "description", type: "text" },
      { name: "color", type: "varchar" },
      { name: "isSystem", type: "tinyint" },
      { name: "permissions", type: "json" },
      { name: "createdAt", type: "datetime" },
      { name: "updatedAt", type: "datetime" },
      { name: "version", type: "int" },
    ],
    jsonColumns: ["permissions"],
    timestamps: ["createdAt","updatedAt"],
  },
  users: {
    table: "users",
    primaryKey: "id",
    columns: [
      { name: "id", type: "bigint" },
      { name: "username", type: "varchar" },
      { name: "fullName", type: "varchar" },
      { name: "email", type: "varchar" },
      { name: "phone", type: "varchar" },
      { name: "title", type: "varchar" },
      { name: "department", type: "varchar" },
      { name: "roleId", type: "bigint" },
      { name: "roleCode", type: "varchar" },
      { name: "roleName", type: "varchar" },
      { name: "status", type: "enum" },
      { name: "avatar", type: "text" },
      { name: "color", type: "varchar" },
      { name: "passwordHash", type: "varchar" },
      { name: "passwordSalt", type: "varchar" },
      { name: "lastLoginAt", type: "datetime" },
      { name: "createdAt", type: "datetime" },
      { name: "updatedAt", type: "datetime" },
      { name: "notes", type: "text" },
      { name: "version", type: "int" },
    ],
    jsonColumns: [],
    timestamps: ["createdAt","updatedAt"],
  },
  auditLogs: {
    table: "auditLogs",
    primaryKey: "id",
    columns: [
      { name: "id", type: "bigint" },
      { name: "userId", type: "bigint" },
      { name: "userName", type: "varchar" },
      { name: "userRole", type: "varchar" },
      { name: "action", type: "varchar" },
      { name: "module", type: "varchar" },
      { name: "entityId", type: "varchar" },
      { name: "description", type: "text" },
      { name: "details", type: "text" },
      { name: "ipAddress", type: "varchar" },
      { name: "timestamp", type: "datetime" },
      { name: "version", type: "int" },
    ],
    jsonColumns: [],
    timestamps: [],
  },
};

export function getResource(name: string): ResourceDef | undefined {
  return RESOURCES[name];
}

export function isValidColumn(def: ResourceDef, name: string): boolean {
  return def.columns.some((c) => c.name === name);
}
